### ISSUE TITLE
Wonderful Subs down?

### ISSUE THREAD

**Issue by Ichijoe2112** [DxCx/plugin.video.wonderfulsubs#112] opened 2019-11-05 17:11 UTC
Just wondering if it's just me, or if WS is not working at the moment. It's been like that since last Saturday (20191102). Since this time I've been getting a "0 (Zero) Sources found" error everytime I try to open something up.

I'm using Kodi 18.4 on my nVidia Shield Pro (2015).

I thought I'd post this here since nobody else has. If only to be told that its just me.

Thanks.

**Comment by bsmith456** [comment] 2019-11-05 18:44
I'm having same issue for the past couple weeks,theirs a few i can get to work but wasn't having a problem until last week

**Comment by Ichijoe2112** [comment] 2019-11-06 18:27
Ok good to know. It was also broken around before the last update (~ca.11 days ago as of writing? IIRC), then it worked fine till last Saturday, and for me has been down since.

**Comment by Jkrise** [comment] 2019-11-10 02:39
Alt search seems to work for most of the things that find zero sources, at least for me so far

**Comment by Arcires** [comment] 2019-11-15 09:30
I've been having the same issue as described. Anyone know if it's related to the API services from WonderfulSubs, Kodi itself or DxCx?

**Comment by Ichijoe2112** [comment] 2019-11-15 19:06
I wonder if the Devs have abandoned us? I just read something about how OneNation, and UKTV had their collets felt up, and had to close up shop. I mean I expect things like this to happen. But, I can't recall a time that 9Anime was ever down this this long.*

*i.e. Back when it was still supported.

**Comment by DxCx** [comment] 2019-11-15 19:14
Im still here
I dont use the addon day to day anymore so i havent notice its broken.. :/
Will check it out tommrow

**Comment by Ichijoe2112** [comment] 2019-11-15 21:04
Thank you for your work

**Comment by DxCx** [comment] 2019-11-16 16:47
well, looks like @SwagOtaku fixed this long ago, i merged tthe fix and forgot tto release new version..
please check latest and report back ;)
sorry for the delay.. :\

**Comment by RedNinjaX** [comment] 2019-11-16 19:47
@DxCx that fix is old. Things changed since then and now the new fix needed is to set the user agent to `AppleCoreMedia/1.0.0.16E227 (iPhone; U; CPU OS 12_2 like Mac OS X; en_us)`. You night as well set that as the overall header, so you can just replace the value of _USER_AGENT with the one above instead and everything should work again (hopefully). If that doesn't work you'll have to set the user-agent of the actually video link request itself.

**Comment by doko-desuka** [comment] 2019-11-17 09:17
I tried creating an embed extractor for Hy***x. Although it gets an M3U8 using a mobile user-agent, when Kodi tries to play it it fails when trying to get the HLS encryption key (it's a separate request to a URL in the playlist, seen in the EXT-X-KEY setup).  

Anyway, you can find the extractor here, maybe it helps:  
https://gist.github.com/doko-desuka/faa8d470d72b61373612973959a7a0e6

Also, as it is, control.play_source() needs to be modified to append Kodi-style HTTP headers (mostly User-Agent, Referer and Origin), like in that wiki link.

**Comment by DxCx** [comment] 2019-11-17 19:34
doesnt look 

> I tried creating an embed extractor for Hy***x. Although it gets an M3U8 using a mobile user-agent, when Kodi tries to play it it fails when trying to get the HLS encryption key (it's a separate request to a URL in the playlist, seen in the EXT-X-KEY setup, the debug log says it's got a HTTP 400 "Bad Request" response).
> 
> Anyway, you can find the extractor here, maybe it helps:
> https://gist.github.com/doko-desuka/faa8d470d72b61373612973959a7a0e6
> 
> Also, as it is, control.play_source() needs to be modified to append Kodi-style HTTP headers (mostly User-Agent, Referer and Origin), like in that wiki link. That "makeKodiHeaders" function is this:
> 
> ```
>     def makeKodiHeaders(self, session):
>         if isinstance(session, dict):
>             # A direct dict.
>             return '|' + '&'.join(key + '=' + quote_plus(value) for key, value in session.items())
>         else:
>             # A session object.
>             temp = '|' + '&'.join(key + '=' + quote_plus(value) for key, value in session.headers.items())
>             # Only add cookies if present.
>             return (temp + '&Cookie=' + quote_plus(session.getCookieHeaderString())) if session.cookies else temp
> ```

doesnt look like i'll have time to get into it soon :( 
howeverr if anyone wanna give it a try and open a PR i'll happly merge it..

**Comment by DxCx** [comment] 2019-11-17 19:35
> @DxCx that fix is old. Things changed since then and now the new fix needed is to set the user agent to `AppleCoreMedia/1.0.0.16E227 (iPhone; U; CPU OS 12_2 like Mac OS X; en_us)`. You might as well set that as the overall header, so you can just replace the value of _USER_AGENT with the one above instead and everything should work again (hopefully). If that doesn't work you'll have to set the user-agent of the actually video link request itself. If you don't know, @doko-desuka said the way to do that can be found here: https://kodi.wiki/view/HTTP#HTTP.2FHTTPS_url_format
> 
> An example being:
> `"https://bla.com/video.mp4" + makeKodiHeaders(myRequestsSession) # Join the two strings: the media and Kodi (FFMpeg) headers. `
> 
> I did some stuff on the backend that should handle any redirects properly.

Hey @RedNinjaX Thanks, i've released new version (0.0.27) with this user-agent.
please give the new release a try and let me know if it works for you (for me both the 0.0.26 and 0.0.27 works..)

**Comment by RedNinjaX** [comment] 2019-11-17 19:42
Awesome! When I get home I'll have to make some adjustments to the server again to see if it will work.

**Comment by doko-desuka** [comment] 2019-11-18 02:43
I'm thinking the internal key request might not use the right headers (maybe Fiddler can show what it is).  
If that's the case, then the key URLs in the M3U8 need to be replaced/proxied, like they suggest in here: https://blog.jonlu.ca/posts/illegal-streams.

**Comment by doko-desuka** [comment] 2019-11-18 06:55
Fiddler says Kodi is using the right headers to ask for the M3U8 key, so I don't know what can be done. It's outside my skillset.  

```
GET https://i.william-crocker.xyz?hash=56A6Yjg2cdYDYjKluLqoAA HTTP/1.1
User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 7 Build/MOB30X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
Host: i.william-crocker.xyz
Icy-MetaData: 1
Accept: */*
Accept-Language: en-US,en;q=0.5
Connection: close
DNT: 1
Origin: https://replay.watch
Referer: https://replay.watch/hydrax.html?r=PvbANj&vc=1

HTTP/1.1 400 Bad Request
Server: cloudflare
Date: Mon, 18 Nov 2019 06:24:44 GMT
Content-Type: text/html
Content-Length: 155
Connection: close
CF-RAY: -  
```

**Comment by RedNinjaX** [comment] 2019-11-18 11:37
@doko-desuka I know exactly what the problem is now! When I was testing out downloading from HydraX with FFMPEG I kept running into the same error until I manually downloaded the key file and set the key url to the local directory of the key file. After that, it worked like a charm.

I don't know if it would be possible to have Kodi download a key file on the fly like that and use it for that specific instance (I could always create a special endpoint for retrieving the key file in that case). I just setup everything correctly on the backend a few minutes ago, so if it were possible to do what I said above, it should work.

**Comment by RedNinjaX** [comment] 2019-11-18 12:08
`If that's the case, then the key URLs in the M3U8 need to be replaced/proxied`

Enjoy the add-on guys 😉

@DxCx I don't want to have the backend fetch and return the key for every request (only for Kodi). Can you do me a favor and change the User-agent back to the old one and add a special header to requests such as "Platform" with value "Kodi". If appreciate that 😅

**Closed** 2019-11-18 12:19 UTC

**Comment by doko-desuka** [comment] 2019-11-18 12:23
> I don't know if it would be possible to have Kodi download a key file on the fly like that and use it for that specific instance (I could always create a special endpoint for retrieving the key file in that case). I just setup everything correctly on the backend a few minutes ago, so if it were possible to do what I said above, it should work.

@RedNinjaX I'm pretty sure it's not possible to do that kind of key management with the vanilla FFMpeg player (maybe in [inputstream.adaptive](https://github.com/peak3d/inputstream.adaptive/issues/89#issuecomment-342787406)? This comment shows a way I think).  
Did you find out what the is error, exactly? If I request it manually through Python it works, so I don't know why FFMpeg would fail at that.  

So I can only think of that proxy solution, something like replacing the key URL(s) with others, and maybe having the headers as url-encoded parameters like https://site.com/api/key?url=https%3A%2F%2Fother-site.com%2Fa228387ec9b78d&headers=%7B%22User-Agent%22%3A%22blablabla%22%2C%20%22Referer%22%3A%22bliblibli%22%2C%20%22Origin%22%3A%22xyz123%22%7D  
But all of this falls outside my skillset.  

PS: I think it's safer not to use the site name, so they can't find this discussion on a web search lol

**Comment by RedNinjaX** [comment] 2019-11-18 12:26
@doko-desuka the issues closed. The add-ons fixed now. That's exactly what I'd did. Thank you for all your help. I can't fully express my gratitude through text unfortunately 😅 Genuinely could not have resolved this without you.

**Comment by doko-desuka** [comment] 2019-11-19 05:01
@RedNinjaX

**Comment by doko-desuka** [comment] 2019-11-19 05:02
Oops, typo, sorry.

> `https://www.wonderfulsubs.com/api/media/playlist? (...)`

@RedNinjaX Oh, now I've seen what you did. That's beautiful!

**Comment by RedNinjaX** [comment] 2019-11-19 05:27
@doko-desuka yeaaahh it kind of is. I'm already noticing the impact. Might have to upgrade the server to a higher tier just to handle it now...

**Comment by doko-desuka** [comment] 2019-11-19 05:33
I'll reach out on Discord.
